### ISSUE TITLE
[Bug] 插件版本1.3.1后无法正常使用Gemini

### ISSUE THREAD

**Issue by StarDuster** [ZiuChen/ChatGPT-Next-Web#3]
### 📦 Deployment Method

Other

### 📌 Version

1.3.1

### 💻 Operating System

Windows

### 📌 System Version

11

### 🌐 Browser

Other

### 📌 Browser Version

utools

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/17b68afb-43fd-4669-948d-14238cf6836d)
![image](https://github.com/user-attachments/assets/037b7258-7289-496f-bb9b-77bb3ac7bb9b)

对比最新部署在vercel的nextchat和utools插件的版本，看起来上游代码是没问题，而看上去插件的版本没有正确带上API KEY

**Comment by zhefox** [comment]
补充问题大概率是因为路径处key的添加位置出错了
![image](https://github.com/user-attachments/assets/13daeeee-25c5-4c43-9b84-a4bf0aebcbeb)

**Comment by ZiuChen** [comment]
> 补充问题大概率是因为路径处key的添加位置出错了 ![image](https://private-user-images.githubusercontent.com/77232781/355336828-13daeeee-25c5-4c43-9b84-a4bf0aebcbeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTg2OTQsIm5iZiI6MTcyMjk5ODM5NCwicGF0aCI6Ii83NzIzMjc4MS8zNTUzMzY4MjgtMTNkYWVlZWUtMjVjNS00YzQzLTliODQtYTRiZjBhZWJjYmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAyMzk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YWEwNzVmZmQ4M2VlZWMxOTkyODY3YzI0MGExMTYyYWIxMGRkMDdmODlkNWY5ZWY5YjIzZjA2NTczN2M2NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OHbRWemf2B5I6gnnSecMU3MuraYtIGqvHILot-8_WVg)

辛苦测试下 https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.14.1 版本是否会有问题呢？

**Comment by zhefox** [comment]
> > 补充问题大概率是因为路径处key的添加位置出错了 ![image](https://private-user-images.githubusercontent.com/77232781/355336828-13daeeee-25c5-4c43-9b84-a4bf0aebcbeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5OTg2OTQsIm5iZiI6MTcyMjk5ODM5NCwicGF0aCI6Ii83NzIzMjc4MS8zNTUzMzY4MjgtMTNkYWVlZWUtMjVjNS00YzQzLTliODQtYTRiZjBhZWJjYmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDAyMzk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0YWEwNzVmZmQ4M2VlZWMxOTkyODY3YzI0MGExMTYyYWIxMGRkMDdmODlkNWY5ZWY5YjIzZjA2NTczN2M2NWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OHbRWemf2B5I6gnnSecMU3MuraYtIGqvHILot-8_WVg)
> 
> 辛苦测试下 https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/releases/tag/v2.14.1 版本是否会有问题呢？

似乎没问题了

**Comment by StarDuster** [comment]
感谢各位，新版我这边正常了
